[phases.setup]
# Install required runtimes and tools directly from nixpkgs
# - python311 + uv: for Polygon MCP (uvx)
# - nodejs_18: Node runtime
# - pnpm: package manager used by the project
nixPkgs = ["python311", "uv", "nodejs_18", "pnpm"]

[start]
cmd = "pnpm start"

