[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
# Install Python and uv directly from nixpkgs (no pip needed!)
nixPkgs = ["python311", "uv"]

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

