services:
  - type: web
    name: stock-ai-advisor
    env: node
    region: oregon # Change to your preferred region (oregon, frankfurt, singapore, ohio)
    plan: starter # $7/month - or use 'free' for 750 hrs/month (note: free tier sleeps after 15 min inactivity)
    
    # Note: Render Node environment doesn't support Python subprocesses needed for Polygon MCP
    # For full MCP functionality, deploy to Railway instead: https://railway.app
    
    # Auto-deploy on push to main
    autoDeploy: true
    branch: main
    
    # Health check (optional but recommended)
    healthCheckPath: /
    
    # Environment variables (set these in Render Dashboard)
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false # Set manually in dashboard for security
      - key: POLYGON_API_KEY
        sync: false # Set manually in dashboard for security
      - key: VECTORIZE_PIPELINE_ACCESS_TOKEN
        sync: false
      - key: VECTORIZE_ORGANIZATION_ID
        sync: false
      - key: VECTORIZE_PIPELINE_ID
        sync: false

